### ISSUE TITLE
parallelize at molecule granularity level

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/smi2sdf3d#1]
each molecule in the input file should be handled by a different process

**Comment by CKannas** [comment]
You can use concurrent.futures package to create a pool of processes and then create jobs (one or more mols per job) for the process pool to execute.

**Comment by UnixJunkie** [comment]
contributions are welcome ;)

**Comment by UnixJunkie** [comment]
this can be done by other tools (PAR or GNU parallel) also

**Comment by UnixJunkie** [comment]
I will not do that.
